intrusive_ptr: intrusive_ptr.cpp
	g++ intrusive_ptr.cpp -o intrusive_ptr -I- -I../../ -ftemplate-depth-50 -L/usr/local/lib -llua -llualib
#	g++ intrusive_ptr.cpp -g -o intrusive_ptr -I- -I../../ -I/scratch/lua-5.0/include -I/scratch/boost_1_30_0 -ftemplate-depth-50 -L/scratch/lua-5.0/lib -llua -llualib

