any_converter: any_converter.cpp
	g++ any_converter.cpp -g -o any_converter -I- -I../../ -ftemplate-depth-50 -L/usr/local/lib -llua -llualib
#	g++ any_converter.cpp -g -o any_converter -I- -I../../ -I/scratch/lua-5.0/include -I/scratch/boost_1_30_0 -ftemplate-depth-50 -L/scratch/lua-5.0/lib -llua -llualib

