glut_test: glut_bind.cpp
	g++ glut_bind.cpp -o glut_bind -I- -I../../ -ftemplate-depth-50 -I/usr/X11R6/include -L/usr/X11R6/lib -L/usr/local/lib -L../../lib -lluabind -lX11 -lXi -lXmu -lglut -lGL -lGLU -lm -llua -llualib

