glut_test: glut_bind.cpp
	g++ glut_bind.cpp -o glut_bind -I- -I../../ -ftemplate-depth-50 -I/usr/X11R6/include -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXi -lXmu -lglut -lGL -lGLU -lm -llua -llualib
#	g++ glut_bind.cpp -g -o glut_bind -I- -I../../ -I/scratch/lua-5.0-beta/include -I/scratch/boost_1_30_0 -ftemplate-depth-50 -I/usr/X11R6/include -L/usr/X11R6/lib -L/scratch/lua-5.0-beta/lib -lX11 -lXi -lXmu -lglut -lGL -lGLU -lm -llua -llualib

